### ISSUE TITLE
Cannot import environment on a OSX

### ISSUE THREAD

**Issue by augustasvilc** [josedvq/mma-lab#1]
Hello,

when I try to import the environment on OSX I get this error:
ResolvePackageNotFound: 
  - libstdcxx-ng=9.1.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - freeglut=3.0.0
  - libglu=9.0.0
I get it because these packages are not available for mac on anaconda. There are some of them
(freeglut, libgfortran-ng) for which there exist old versions of the package when they were still supported for os-x but for others there are no such packages for OSX, I would like to know if and how this issue can be solved.

**Comment by augustasvilc** [comment]
A workaround is to delete these packages from the .yml file and install it without them. Some dependencies are missing for some of the labs but can be downloaded along the way.

**Comment by shivanisgithub** [comment]
I have the same issue! How did you download the missing dependencies for the labs if they weren't available for Mac on anaconda? @vilaug

**Comment by augustasvilc** [comment]
Pretty sure I just used `pip install` individually but can't be sure
